"""
Kindle Clippings Splitter

This script parses the 'My_Clippings.txt' file generated by Amazon Kindle devices.
It reads the raw, unstructured clippings (highlights, notes, and bookmarks),
separates them by book title, and saves the organized notes into individual text files 
inside a dedicated output directory. 

Version: 1.0.0
"""

__version__ = "1.0.0"

import os
import re

def sanitize_filename(raw_name: str) -> str:
    """Cleans and formats the book title to be used as a safe filename."""
    clean_name = raw_name.upper().replace(" ", "_").replace(".", "")
    # Remove OS-forbidden characters (\ / : * ? " < > |)
    clean_name = re.sub(r'[\\/*?:"<>|]', "", clean_name)
    return clean_name[:100]

def parse_clippings(file_path: str) -> dict:
    """Reads My_Clippings.txt and groups notes by sanitized book names."""
    if not os.path.exists(file_path):
        raise FileNotFoundError(f"Source file not found: {file_path}")
        
    book_notes = {}
    
    # 'utf-8-sig' automatically handles the BOM marker
    with open(file_path, "r", encoding="utf-8-sig") as f:
        content = f.read()

    blocks = [b.strip() for b in content.split("==========") if b.strip()]

    for block in blocks:
        lines = block.splitlines()
        if not lines:
            continue
            
        raw_book_name = lines[0].strip()
        clean_name = sanitize_filename(raw_book_name)
        
        block_text = block + "\n==========\n"
        
        if clean_name in book_notes:
            book_notes[clean_name] += block_text
        else:
            book_notes[clean_name] = block_text
            
    return book_notes

def save_book_notes(book_notes: dict, output_dir: str = "books", log_path: str = "log.txt"):
    """Saves grouped notes into individual files and logs any errors."""
    os.makedirs(output_dir, exist_ok=True)
    
    with open(log_path, "w", encoding="utf-8") as log:
        for book_name, text in book_notes.items():
            book_fname = os.path.join(output_dir, f"{book_name}.txt")
            try:
                with open(book_fname, "w", encoding="utf-8") as book_file:
                    book_file.write(text)
            except Exception as e:
                print(f"Error saving book: {book_name}")
                log.write(f"Error with file {book_name}: {str(e)}\n")

def main():
    """Main execution flow."""
    input_file = "My_Clippings.txt"
    
    # Fallback to test file if the real Kindle file isn't present
    if not os.path.exists(input_file) and os.path.exists("test_clippings.txt"):
        input_file = "test_clippings.txt"
        print("Real 'My_Clippings.txt' not found. Using 'test_clippings.txt' for demonstration.")
    
    try:
        print(f"Parsing clippings from '{input_file}'...")
        notes = parse_clippings(input_file)
        
        print("Saving files per book...")
        save_book_notes(notes)
        
        print("Splitting completed successfully!")
    except Exception as e:
        print(f"Critical error during execution: {e}")

if __name__ == "__main__":
    main()